version: "3.9"

services:
  selenium-chrome:
    build:
      context: ./
    # image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_NODE_SESSION_TIMEOUT=86400  # en segundos (24 horas)
    shm_size: "2g"
    networks:
      - selenium_net

  selenium-client:
    build:
      context: ./selenium_client
    container_name: selenium-client
    depends_on:
      - selenium-chrome
    volumes:
      - ./selenium_client:/app
    networks:
      - selenium_net
    # command: ["python", "script.py"]
    command: ["tail", "-f", "/dev/null"]

networks:
  selenium_net:
    driver: bridge
