version: "3.8"

services:
  selenium:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: selenium-chrome-visual
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"
    volumes:
      - ./scripts:/usr/src/app/scripts
      - ./capturas:/usr/src/app/capturas
    stdin_open: true
    tty: true
